spring:
  application:
    name: auth-service
  redis:
    host: 192.168.0.100
    database: 0

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/




